name: Build & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CONTAINER_NAME: $web

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v3
      with:
        node-version: 14.18.1
        cache: 'npm'
    - run: npm ci
    - name: Setup host file
      run: |
        sudo echo "20.187.121.32 sccm.dev.local" | sudo tee -a /etc/hosts
    - run: npm run export:production
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
        container_name: $CONTAINER_NAME 
        source_dir: /out
