name: Build & Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v3
      with:
        node-version: 14.18.1
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: |
        find .next -type f -name "*.html"
        cp --parents `find .next -type f -name "*.html"` /out/
        ls
    
